export type Config = {
  PLAYER_1_INITIAL_MANA: number;
  PLAYER_2_INITIAL_MANA: number;
  MAX_MANA_INCREASE_PER_TURN: number;
  MAX_MANA: number;

  PLAYER_1_INITIAL_HAND_SIZE: number;
  PLAYER_2_INITIAL_HAND_SIZE: number;
  MAX_HAND_SIZE: number;
  CARDS_DRAWN_PER_TURN: number;
  SHUFFLE_DECK_ON_GAME_START: boolean;
  MAX_CARD_REPLACES_PER_TURN: number;
  DRAW_STEP: 'turn-start' | 'turn-end';

  PLAYER_1_SHOULD_DRAW_ON_FIRST_TURN: boolean;
  PLAYER_2_SHOULD_DRAW_ON_FIRST_TURN: boolean;

  MAX_RESOURCE_ACTION_PER_TURN: number;
  MAX_MULLIGANED_CARDS: number;

  MAX_MOVEMENT_PER_TURN: number;
  MAX_ATTACKS_PER_TURN: number;
  MAX_COUNTERATTACKS_PER_TURN: number;

  MAX_EQUIPED_ARTIFACTS: number;

  SHUFFLE_DECK_AT_START_OF_GAME: boolean;

  BASE_UNIT_SPEED: number;
};

export const defaultConfig: Config = {
  MAX_HAND_SIZE: 6,
  CARDS_DRAWN_PER_TURN: 2,
  MAX_MANA_INCREASE_PER_TURN: 1,
  MAX_MANA: 9,
  MAX_RESOURCE_ACTION_PER_TURN: 1,
  MAX_MULLIGANED_CARDS: 3,
  MAX_MOVEMENT_PER_TURN: 1,
  MAX_ATTACKS_PER_TURN: 1,
  MAX_COUNTERATTACKS_PER_TURN: Infinity,
  SHUFFLE_DECK_ON_GAME_START: true,
  DRAW_STEP: 'turn-start',
  PLAYER_1_INITIAL_HAND_SIZE: 3,
  PLAYER_2_INITIAL_HAND_SIZE: 3,
  PLAYER_1_INITIAL_MANA: 2,
  PLAYER_2_INITIAL_MANA: 3,
  PLAYER_1_SHOULD_DRAW_ON_FIRST_TURN: false,
  PLAYER_2_SHOULD_DRAW_ON_FIRST_TURN: false,
  MAX_CARD_REPLACES_PER_TURN: 1,
  MAX_EQUIPED_ARTIFACTS: 3,
  SHUFFLE_DECK_AT_START_OF_GAME: true,
  BASE_UNIT_SPEED: 2
};

export const IMMUTABLE_CONFIG = {
  MIN_DECK_SIZE: 30,
  MAX_DECK_SIZE: 45,
  MAX_ALLOWED_CARD_COPIES: 999
};
