export type Config = {
  HERO_DECK_SIZE: number;
  HERO_DECK_MAX_CARD_COPIES: number;

  INITIAL_MP: number;
  MAX_MP: number;
  MP_REGEN_PER_TURN: number;

  INITIAL_HAND_SIZE: number;
  MAX_HAND_SIZE: number;
  CARDS_DRAWN_PER_TURN: number;
  SHUFFLE_DECK_ON_GAME_START: boolean;
  MAX_CARD_REPLACES_PER_TURN: number;

  MAX_MOVEMENT_PER_TURN: number;
  MAX_ATTACKS_PER_TURN: number;

  MAX_AP: number;
  AP_COST_PER_MOVE: number;
  AP_COST_PER_ATTACK: number;
  AP_COST_INCREASE_PER_ATTACK: number;
  AP_COST_PER_CARD: number;

  BASE_ATTACK_DAMAGE: number;

  EXP_REWARD_PER_ATTACK: number;
  EXP_REWARD_PER_TURN: number;
};

export const defaultConfig: Config = {
  HERO_DECK_SIZE: 20,
  HERO_DECK_MAX_CARD_COPIES: 4,

  INITIAL_MP: 2,
  MAX_MP: 5,
  MP_REGEN_PER_TURN: 2,

  INITIAL_HAND_SIZE: 3,
  MAX_HAND_SIZE: 10,
  SHUFFLE_DECK_ON_GAME_START: true,
  CARDS_DRAWN_PER_TURN: 1,
  MAX_CARD_REPLACES_PER_TURN: 1,

  MAX_MOVEMENT_PER_TURN: Infinity,
  MAX_ATTACKS_PER_TURN: Infinity,

  MAX_AP: 3,
  AP_COST_PER_MOVE: 1,
  AP_COST_PER_ATTACK: 1,
  AP_COST_INCREASE_PER_ATTACK: 1,
  AP_COST_PER_CARD: 1,

  BASE_ATTACK_DAMAGE: 1,

  EXP_REWARD_PER_ATTACK: 1,
  EXP_REWARD_PER_TURN: 1
};
